name: Build and Push Docker Images
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.GH_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/staytus:main
    - name: Push the Docker image to Docker Hub
      run: docker push ${{secrets.DOCKER_USER}}/staytus:main
    - name: Push the Docker image to GitHub Container Registry
      run: |
        docker tag ${{secrets.DOCKER_USER}}/staytus:main ghcr.io/${{secrets.DOCKER_USER}}/staytus:main
        docker push ghcr.io/${{secrets.DOCKER_USER}}/staytus:main
